config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users do 
    member do 
      get 'status'
    end
  end 

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'
  get 'reset_password' => 'users#reset_password'
  post 'reset_password' => 'users#reset_password_email'
  get 'resetp/:id' => 'users#new_password'
  patch 'resetp' => 'users#update_password'
  post 'resetp' => 'users#update_password'

  get '/auth/failure', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create_omniauth'
  
  namespace :account do
    get 'profile/edit' => 'profile#edit'
    patch 'profile/edit' => 'profile#update'
    resources :affiliate
		resources :logs
    resources :webauthn_credentials
  end
  
  namespace :admin do
    resources :sessions
    post 'passkey_login' => 'sessions#passkey_login'
    
    root 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    get 'clear_cache' => 'dashboard#clear_cache'
    get 'login' => 'sessions#new'
    get 'logout' => 'sessions#destroy'
    get 'password_reset' => 'system/users#password_reset'
    get 'users/random' => 'system/users#random'
    get 'search' => 'search#index'

    namespace :system do
      post 'printers/print_url' => 'printers#print_url'
      resources :webauthn_credentials

      resources :users do
        member do
          get 'logins' => 'users#show'
          get 'login' => 'users#login'
          get 'extra_properties'
          get 'welcome_email'
        end
      end
      resources :affiliates do
        member do
          get 'extra_properties'
          get 'categories'
          post 'categories' => 'affiliates#create_categories'
        end
      end

      resources :roles
      resources :settings
      resources :logs
      resources :notifications
      resources :notification_subscriptions
      resources :events do
        member do
          get 'resend'
        end
      end
      resources :event_types
      resources :categories
      resources :search_paths
      resources :attributes
      resources :extra_properties
      resources :printers
      resources :domains do 
        member do 
          get 'set_current'
        end
      end
    end
  end
end

app/controllers/admin/system/affiliates_controller.rb
class Admin::System::AffiliatesController < Admin::BaseController

  def index
    authorize Affiliate.new

    @affiliates = Affiliate.order(sort_column + " " + sort_direction)
    @affiliates = @affiliates.where("name LIKE '%#{params[:q]}%' OR code = '#{params[:q]}'") unless params[:q].blank?

    unless params[:c].blank?
      @category = Category.find_by(slug: params[:c], entity_type: :affiliate)
      @affiliates = @affiliates.joins(:affiliate_categories).where("core_affiliate_categories.category_id = #{@category.id}")
    end

    respond_to do |format|
      format.html { @affiliates = @affiliates.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Affiliate.to_csv(@affiliates) }
    end
  end

  def new
    @affiliate = authorize Affiliate.new(name: 'New affiliate', active: true, country: Cache.setting(:system, "Default Country"))
    render 'edit'
  end

  def create
    @affiliate = authorize Affiliate.new(affiliate_params)

    if @affiliate.save
      unless params[:c].blank?
        c = Category.find_by(entity_type: :affiliate, slug: params[:c])
        AffiliateCategory.create(affiliate_id: @affiliate.id, category_id: c.id) unless c.nil?
      end
      redirect_to action: 'show', id: @affiliate.id, notice: 'Affiliate was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @affiliate = authorize Affiliate.find(params[:id])
  end

  def edit
    @affiliate = authorize Affiliate.find(params[:id])
  end

  def update
    @affiliate = authorize Affiliate.find(params[:id])

    if @affiliate.update(affiliate_params)
      redirect_to action: 'show', id: @affiliate.id, notice: 'Affiliate was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @affiliate = authorize Affiliate.find(params[:id])
    @affiliate.destroy

    redirect_to action: 'index', notice: 'Affiliate has been deleted.'
  end

  def extra_properties
    @affiliate = Affiliate.find(params[:id])
    authorize @affiliate, :show?
    5.times { @affiliate.extra_properties.build }
  end

  def categories
    @affiliate = Affiliate.find(params[:id])
    authorize @affiliate, :show?
  end

  def create_categories
    authorize Affiliate, :update?

    AffiliateCategory.where(affiliate_id: params[:id]).delete_all
    category_ids = params[:category_ids]

    unless category_ids.nil?
      category_ids.each do |id|
        AffiliateCategory.create affiliate_id: params[:id], category_id: id
      end
    end

    redirect_to action: 'show', id: params[:id], notice: 'Affiliate was successfully updated.'
  end

  def products
    @affiliate = Affiliate.includes(:products, [products: :product]).find(params[:id])
    authorize @affiliate, :show?
  end

  def create_products
    authorize Affiliate, :update?

    params[:product_ids].each { |id| AffiliateProduct.create product_id: id, affiliate_id: params[:id] }
    redirect_back(fallback_location: admin_root_path)
  end

  def remove_products
    authorize Affiliate, :update?

    AffiliateProduct.delete_all id: params[:affiliate_product_ids]
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def affiliate_params
    params.require(:affiliate).permit!
  end

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/admin/system/attributes_controller.rb
class Admin::System::AttributesController < Admin::BaseController

  def index
    @attributes = Attribute.where(entity_type: params[:type]).order("sort")
  end

  def new
    @attribute = Attribute.new
    @attribute.entity_type = params[:type]
    @attribute.name = 'New attribute'
    render 'edit'
  end

  def create
    @attribute = Attribute.new(attribute_params)

    if @attribute.save
      redirect_to action: 'index', type: @attribute.entity_type, notice: 'Attribute was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @attribute = Attribute.find(params[:id])
  end

  def edit
    @attribute = Attribute.find(params[:id])
  end

  def update
    @attribute = Attribute.find(params[:id])

    if @attribute.update(attribute_params)
      redirect_to action: 'index', type: @attribute.entity_type, notice: 'Attribute was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @attribute = Attribute.find(params[:id])
    @attribute.destroy
    redirect_to action: 'index', type: @attribute.entity_type, notice: 'Attribute has been deleted.'
  end


  private

  def attribute_params
    params.require(:attribute).permit!
  end


end

app/controllers/admin/system/categories_controller.rb
class Admin::System::CategoriesController < Admin::BaseController

  def index
    @categories = Category.select("id, name, code, parent_id, slug, sort, hidden")
                          .where(entity_type: params[:type])
                          .order(:sort)
  end

  def new
    @category = Category.new entity_type: params[:type], parent_id: params[:parent_id], name: 'New category'

    @category.sort = Category.where(entity_type: params[:type], parent_id: params[:parent_id]).maximum(:sort)
    @category.sort = 0 if @category.sort.nil?
    @category.sort = @category.sort + 1

    render 'edit'
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to action: 'index', type: @category.entity_type, notice: 'Category was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      Rails.cache.delete @category
      redirect_to action: 'index', type: @category.entity_type, notice: 'Category was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])

    Rails.cache.delete @category
    @category.destroy

    redirect_to action: 'index', type: @category.entity_type, notice: 'Category has been deleted.'
  end


  private

  def category_params
    params.require(:category).permit!
  end

end

app/controllers/admin/system/domains_controller.rb
class Admin::System::DomainsController < Admin::BaseController

  def index
    authorize Domain.new
    @domains = Domain.order(:name)

    respond_to do |format|
      format.html { @domains = @domains.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Domain.to_csv(@domains) }
    end
  end

  def new
    @domain = authorize Domain.new(name: 'New domain')
    render 'edit'
  end

  def create
    @domain = authorize Domain.new(domain_params)

    if @domain.save
      Rails.cache.delete :domains
      redirect_to action: 'index', notice: 'Domain was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @domain = authorize Domain.find(params[:id])
  end

  def edit
    @domain = authorize Domain.find(params[:id])
  end

  def update
    @domain = authorize Domain.find(params[:id])

    if @domain.update(domain_params)
      Rails.cache.delete :domains
      redirect_to action: 'index', notice: 'Domain was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @domain = authorize Domain.find(params[:id])
    @domain.destroy

    Rails.cache.delete :domains
    redirect_to action: 'index', notice: 'Domain has been deleted.'
  end

  def set_current
    cookies[:domain_id] = {:value => params[:id], :expires => 1.year.from_now}
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def domain_params
    params.require(:domain).permit!
  end
end

app/controllers/admin/system/event_types_controller.rb
class Admin::System::EventTypesController < Admin::BaseController

  def index
    authorize EventType.new
    @event_types = EventType.order(:name)
                            .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @event_type = authorize EventType.new
    render 'edit'
  end

  def create
    @event_type = authorize EventType.new(event_type_params)

    if @event_type.save
      redirect_to action: 'index', notice: 'Event Type was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @event_type = authorize EventType.find(params[:id])
  end

  def edit
    @event_type = authorize EventType.find(params[:id])
  end

  def update
    @event_type = authorize EventType.find(params[:id])

    if @event_type.update(event_type_params)
      redirect_to action: 'index', notice: 'Event Type was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @event_type = authorize EventType.find(params[:id])
    @event_type.destroy
    redirect_to action: 'index', notice: 'Event Type has been deleted.'
  end


  private

  def event_type_params
    params.require(:event_type).permit!
  end

end

app/controllers/admin/system/events_controller.rb
class Admin::System::EventsController < Admin::BaseController
  def index
    authorize Event.new
    @events = Event.includes(:event_type)
                   .order(created_at: :desc)
                   .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @event = authorize Event.new
    render 'edit'
  end

  def create
    @event = authorize Event.new(event_params)

    if @event.save
      redirect_to action: 'index', notice: 'Event was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @event = authorize Event.find(params[:id])
  end

  def edit
    @event = authorize Event.find(params[:id])
  end

  def update
    @event = authorize Event.find(params[:id])

    if @event.update(event_params)
      redirect_to action: 'index', notice: 'Event was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @event = authorize Event.find(params[:id])
    @event.destroy
    redirect_to action: 'index', notice: 'Event has been deleted.'
  end

  def resend
    @event = Event.find(params[:id])
    @event.update_column(:processed_at, nil)
    flash[:info] = "Event has been re-dispatched."
    redirect_back(fallback_location: admin_system_events_path)
  end

  private

  def event_params
    params.require(:event).permit!
  end
end

app/controllers/admin/system/extra_properties_controller.rb
class Admin::System::ExtraPropertiesController < ApplicationController

  def create

    params[:extra_properties].each do |h|
      if h[:id].blank?
        ep = ExtraProperty.new(
            extra_property_id: h[:extra_property_id],
            extra_property_type: h[:extra_property_type],
            name: h[:name],
            value: h[:value],
            sort: h[:sort])
      else
        ep = ExtraProperty.find(h[:id])
        ep.assign_attributes(name: h[:name], value: h[:value], sort: h[:sort])
      end

      if ep.is_empty?
        ep.destroy
      else
        ep.save
      end
    end

    flash[:info] = "Extra properties saved"
    redirect_to params[:redirect]
  end

end

app/controllers/admin/system/logs_controller.rb
class Admin::System::LogsController < Admin::BaseController

  def index
    authorize Log.new
    @logs = Log.includes(:user).order(sort_column + " " + sort_direction)
    @logs = @logs.where(loggable_type: params[:type]) unless params[:type].blank?

    respond_to do |format|
      format.html { @logs = @logs.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Log.to_csv(@logs) }
    end
  end

  private

  def sort_column
    params[:sort] || "timestamp"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end

end

app/controllers/admin/system/notification_subscriptions_controller.rb
class Admin::System::NotificationSubscriptionsController < Admin::BaseController

  def index
    authorize NotificationSubscription.new
    @notification_subscriptions = NotificationSubscription.order(created_at: :desc)
                                                          .includes(:user, :event_type, [user: :affiliate])
                                                          .paginate(page: params[:page], per_page: @per_page)

    # filter by event_type if parameter specified
    if params[:event_type_id].present?
      @notification_subscriptions = @notification_subscriptions.where(event_type_id: params[:event_type_id])
    end
  end

  def new
    @notification_subscription = authorize NotificationSubscription.new(user_id: params[:user_id])
    render 'edit'
  end

  def create
    @notification_subscription = authorize NotificationSubscription.new(notification_subscription_params)

    if @notification_subscription.save
      redirect_to_origin(notice: 'Notification was successfully created.')
    else
      render 'edit'
    end
  end

  def show
    @notification_subscription = authorize NotificationSubscription.find(params[:id])
  end

  def edit
    @notification_subscription = authorize NotificationSubscription.find(params[:id])
  end

  def update
    @notification_subscription = authorize NotificationSubscription.find(params[:id])

    if @notification_subscription.update(notification_subscription_params)
      redirect_to_origin(notice: 'Notification was successfully updated.')
    else
      render 'edit'
    end
  end

  def destroy
    @notification_subscription = authorize NotificationSubscription.find(params[:id])
    @notification_subscription.destroy

    redirect_back(fallback_location: { action: "index" })
  end


  private

  def notification_subscription_params
    params.require(:notification_subscription).permit!
  end

end

app/controllers/admin/system/notifications_controller.rb
class Admin::System::NotificationsController < Admin::BaseController

  def index
    authorize Notification.new
    @notifications = Notification.order('created_at DESC')

    respond_to do |format|
      format.html { @notifications = @notifications.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Notification.to_csv(@notifications) }
    end
  end

  def new
    @notification = authorize Notification.new(title: 'New notification', web_delivery: true)
    render 'edit'
  end

  def create
    @notification = authorize Notification.new(notification_params)

    if @notification.save
      redirect_to action: 'index', notice: 'Notification was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @notification = authorize Notification.find(params[:id])
  end

  def edit
    @notification = authorize Notification.find(params[:id])
  end

  def update
    @notification = authorize Notification.find(params[:id])

    if @notification.update(notification_params)
      redirect_to action: 'index', notice: 'Notification was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @notification = authorize Notification.find(params[:id])
    @notification.destroy
    redirect_to action: 'index', notice: 'Notification has been deleted.'
  end


  private

  def notification_params
    params.require(:notification).permit(:title, :start_time, :expire_time, :user_id, :message, :web_delivery, :sms_delivery, :email_delivery)
  end

end

app/helpers/admin/system/webauthn_credentials_helper.rb
module Admin::System::WebauthnCredentialsHelper
end

app/views/admin/system/users/_user.html.erb
<tr>
  <td><%= user.id %></td>
  <td><%= link_to user.name, admin_system_user_path(user) %></td>
  <td><%= user.email %>
  <td><%= user.role.name %></td>
  <td><%= systime user.created_at %></td>
  <td><%= user.status %></td>
  <td class="actions">
    <%= link_to "edit", edit_admin_system_user_path(user) %> &nbsp;
    <%= link_to "delete",
                {action: "destroy", id: user.id},
                method: :delete,
                data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/admin/system/users/edit.html.erb
<h2><i class="fa fa-user"></i> &nbsp;<%= @user.name %></h2>
<hr>

<%= render 'admin/shared/error_messages', object: @user %>

<% if @user.persisted? %>
  <ul class="nav nav-tabs" style="margin-bottom: 20px;">
    <li class="active"><a href="#">Edit</a></li>
    <li><%= link_to "Extra Properties", extra_properties_admin_system_user_path(@user) %></li>
  </ul>
<% end %>

<%= simple_form_for [:admin, :system, @user] do |f| %>

  <div class="col-md-6">
    <%= f.input :password_digest, as: :hidden %>
    <%= f.input :name %>
    <%= f.association :domain %>
    <%= f.association :role %>
    <%= f.input :tag_list, as: :tags %>
    <%= f.association :affiliate, collection: Affiliate.where(active: true).order(:name), input_html: { class: 'chosen-select' } %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :birth_date, as: :datepicker %>
    <%= f.input :gender, collection: ['male', 'female'] %>
    <%= f.input :avatar_url %>
    <%= f.input :vip %>
  </div>

  <div class="col-md-6">
    <%= f.input :status, as: :select, collection: ['active', 'pending', 'suspended', 'deactived', 'Z'] %>

    <%= f.input :pin %>
    <%= f.input :referral_key %>
    <%= f.input :locale %>
    <%= f.input :location %>
    <%= f.input :time_zone %>

    <div class="form-group string optional password">
      <label class="string optional col-sm-3 control-label" for="password">Password</label>
      <div class="col-sm-9">
        <input class="string optional form-control" type="password" name="password" id="password"> (leave blank if not
        updating)
      </div>
    </div>
  </div>

  <div class="col-md-12">
    <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>
  </div>

<% end %>



<% content_for :title do %>
  Users: <%= @user.name %>
<% end %>


<% content_for :menu do
  render "admin/shared/system_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li><%= link_to "Users", admin_system_users_path %></li>
  <% if @user.id.nil? %>
    <li class="active"><%= @user.name %></li>
  <% else %>
    <li><%= link_to @user.name, admin_system_user_path(@user) %></li>
    <li class="active">edit</li>
  <% end %>
<% end %>


<% content_for :head do %>
  <% unless @user.persisted? %>
    <script>
        $(document).ready(function () {
            $("#user_name").select();
        });
    </script>
  <% end %>
  <script>
    $(document).ready(function() {
      $(".chosen-select").chosen({disable_search_threshold: 10});
    });
  </script>
<% end %>

app/views/admin/system/users/extra_properties.html.erb
<h2><i class="fa fa-user"></i> <%= @user.name %></h2>
<hr>

<ul class="nav nav-tabs">
  <li><%= link_to "Edit", edit_admin_system_user_path(@user) %></li>
  <li class="active"><%= link_to "Extra Properties", '#' %></li>
</ul>

<%= render 'admin/shared/extra_properties_list', object: @user, redirect: admin_system_user_path(@user) %>



<% content_for :title do %>
  Users: <%= @user.name %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li><%= link_to "Users", admin_system_users_path %></li>
  <li><%= link_to @user.name, admin_system_user_path(@user) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/system/users/index.html.erb
<div class="pull-right">
  <%= select_tag :role_id, options_from_collection_for_select(Role.all, :id, :name, params[:role_id]), prompt: 'All roles' %> &nbsp;
  <%= select_tag :status, options_for_select(User.distinct(:status).pluck(:status), params[:status]), prompt: 'Any status' %> &nbsp;
  <%= link_to new_admin_system_user_path, class: 'btn btn-sm btn-default' do %>
    <i class="fa fa-plus"></i> New user
  <% end %>
</div>

<h2><i class="fa fa-user"></i> <%= current_domain %> Users</h2>
<hr>

<%= render "admin/shared/search_results_header", object: @users %>


<%= will_paginate @users %>
<table class="table table-striped table-condensed">
  <tr>
    <th><%= sortable "core_users.id", "ID" %></th>
    <th><%= sortable "core_users.name", "Name" %></th>
    <th><%= sortable "email" %></th>
    <th><%= sortable "core_roles.name", "Role" %></th>
    <th><%= sortable "core_users.created_at", "Created" %></th>
    <th><%= sortable "status" %></th>
    <th class="actions">&nbsp;</th>
  </tr>
  <%= render @users %>
</table>

<%= render 'admin/shared/table_summary', data: @users %>



<% content_for :title do %>
  Users
<% end %>

<% content_for :head do %>
  <script>
      $(document).ready(function () {
          $("#role_id, #status").change(function () {
              window.location = "/admin/system/users?role_id=" + $("#role_id").val() + "&status=" + $("#status").val();
          });
      });
  </script>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li class="active">Users</li>
<% end %>

app/views/admin/system/users/password_reset.html.erb
<%= render 'admin/shared/error_messages', object: nil %>


<div class="login-panel panel panel-default">
  <div class="panel-heading">
    <h3 class="panel-title">Reset Password</h3>
  </div>
  <div class="panel-body">
    <%= form_tag reset_password_path do %>
      <fieldset>
        <input type="hidden" name="redirect" value="<%= params[:redirect] %>"/>
        <div class="form-group">
          <%= text_field_tag :email, params[:email], :placeholder => "Email address", :class => "form-control" %>
        </div>

        <%= submit_tag "Send temporary password", :class => "btn btn-info btn-block" %>
      </fieldset>
    <% end %>
  </div>
</div>

app/views/admin/system/users/vouchers.html.erb
<%= render partial: 'admin/shared/user_summary', locals: {user: @user} %>
<%= render partial: 'admin/shared/user_tabs', locals: {user: @user, counts: @counts, selected: :vouchers} %>

<form action="/admin/system/users/<%= @user.id %>/vouchers" method="post" class="pull-right" style="margin: 10px 0 0 0">
  <%= token_tag %>
  <input type="text" name="amount" class="col-md-3" placeholder="$0.0"/> &nbsp;
  <input type="text" name="notes" class="col-md-6" placeholder="notes"/>
  <button class="btn btn-sm btn-default">Add Credit</button>
</form>

<br/><b>Balance:</b> <%= number_to_currency @vouchers.sum { |x| x.amount } %>

<%= will_paginate @vouchers %>
<table class="table table-striped table-condensed">
  <tr>
    <th>Code</th>
    <th>Issued</th>
    <th>Amount</th>
    <th>Related Order</th>
    <th>Notes</th>
  </tr>
  <% @vouchers.each do |uv| %>
    <tr>
      <td>
        <% if uv.voucher_id %>
          <%= uv.voucher.code %>
        <% else %>
          n/a
        <% end %>
      </td>
      <td><%= systime uv.created_at %></td>
      <td><%= number_to_currency(uv.amount) %></td>
      <td>
        <% unless uv.order_id.nil? %>
          <%= link_to uv.order_id.to_s, admin_store_order_path(uv.order_id) %>
        <% else %>
          -
        <% end %>
      </td>
      <td><%= uv.notes %>
  <% end %>
</table>


<%= content_for :title do %>
  Users: <%= @user.name %>
<% end %>


<% content_for :menu do
  render "admin/shared/system_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li><%= link_to "Users", admin_system_users_path %></li>
  <li class="active"><%= @user.name %></li>
<% end %>