config/routes.rb
Rails.application.routes.draw do
  resources :sessions
  resources :users do 
    member do 
      get 'status'
    end
  end 

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'
  get 'register' => 'users#new'
  get 'reset_password' => 'users#reset_password'
  post 'reset_password' => 'users#reset_password_email'
  get 'resetp/:id' => 'users#new_password'
  patch 'resetp' => 'users#update_password'
  post 'resetp' => 'users#update_password'

  get '/auth/failure', to: 'sessions#new'
  get '/auth/:provider/callback', to: 'sessions#create_omniauth'
  
  namespace :account do
    get 'profile/edit' => 'profile#edit'
    patch 'profile/edit' => 'profile#update'
    resources :affiliate
		resources :logs
    resources :webauthn_credentials
  end
  
  namespace :admin do
    resources :sessions
    post 'passkey_login' => 'sessions#passkey_login'
    
    root 'dashboard#index'
    get 'dashboard' => 'dashboard#index'
    get 'clear_cache' => 'dashboard#clear_cache'
    get 'login' => 'sessions#new'
    get 'logout' => 'sessions#destroy'
    get 'password_reset' => 'system/users#password_reset'
    get 'users/random' => 'system/users#random'
    get 'search' => 'search#index'

    namespace :system do
      post 'printers/print_url' => 'printers#print_url'
      resources :webauthn_credentials

      resources :users do
        member do
          get 'logins' => 'users#show'
          get 'login' => 'users#login'
          get 'extra_properties'
          get 'welcome_email'
        end
      end
      resources :affiliates do
        member do
          get 'extra_properties'
          get 'categories'
          post 'categories' => 'affiliates#create_categories'
        end
      end

      resources :roles
      resources :settings
      resources :logs
      resources :notifications
      resources :notification_subscriptions
      resources :events do
        member do
          get 'resend'
        end
      end
      resources :event_types
      resources :categories
      resources :search_paths
      resources :attributes
      resources :extra_properties
      resources :printers
      resources :domains do 
        member do 
          get 'set_current'
        end
      end
    end
  end
end

app/models/affiliate.rb
# == Schema Information
#
# Table name: core_affiliates
#
#  id                  :integer          not null, primary key
#  active              :boolean          default(FALSE), not null
#  api_key             :string(255)
#  city                :string(255)
#  code                :string(255)
#  contact_person      :string(255)
#  country             :string(255)
#  description         :text(65535)
#  disable_invoicing   :boolean          default(FALSE), not null
#  discount_percent    :decimal(5, 2)    default(0.0), not null
#  email               :string(255)
#  enable_edi          :boolean          default(FALSE), not null
#  fax                 :string(255)
#  featured            :boolean          default(FALSE), not null
#  free_shipping       :boolean          default(FALSE), not null
#  logo                :string(255)
#  markup_percent      :decimal(5, 2)    default(0.0), not null
#  name                :string(255)      not null
#  payment_terms       :string(255)
#  phone               :string(255)
#  requires_approval   :boolean          default(FALSE), not null
#  slug                :string(255)      default("")
#  state               :string(255)
#  street1             :string(255)
#  street2             :string(255)
#  summary             :text(65535)
#  tax_exempt          :boolean          default(FALSE), not null
#  transaction_fee     :decimal(5, 2)    default(0.0), not null
#  transaction_percent :decimal(5, 2)    default(0.0), not null
#  website             :string(255)
#  zip                 :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  tax_id              :string(255)
#

class Affiliate < ActiveRecord::Base
  include Exportable
  acts_as_taggable_on :tags
  self.table_name = 'core_affiliates'

  before_save :set_api_key

  has_many :affiliate_categories, dependent: :destroy
  has_many :categories, through: :affiliate_categories
  has_many :extra_properties, -> { order "sort, name" }, as: :extra_property
  has_many :users
  has_many :comments, as: :commentable, dependent: :destroy

  validates_presence_of :name
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, unless: Proc.new { |a| a.email.blank? }
  validates_uniqueness_of :code, unless: Proc.new { |a| a.code.blank? }
  validates_uniqueness_of :name

  # following used only during signup (not stored in database)
  attr_accessor :password, :password_confirmation

  def to_s
    name
  end

  def set_api_key
    self.api_key = SecureRandom.uuid if api_key.blank?
  end

  def address_as_text(opts = {})
    delim = opts[:delimiter] || "\n"

    address = street1.presence || ""
    address = address + delim + street2 unless street2.blank?
    address = address + delim + city unless city.blank?
    address = address + ', ' + state unless state.blank?
    address = address + ', ' + zip unless zip.blank?
    unless opts[:skip_country]
      address += delim + Country[country].to_s unless country.blank?
    end
    address.html_safe unless address.nil?
  end

  def valid_password?

    if password.blank?
      errors.add(:password, "cannot be blank")
      return false
    end

    if password.length < 5
      errors.add(:password, "is too short")
      return false
    end

    if password != password_confirmation
      errors.add(:base, "passwords do not match")
      return false
    end

    return true
  end

  def get_property(name)
    a = extra_properties.find { |x| x.name == name }
    a.nil? ? "" : a.value
  end

  def set_property(name, value)
    a = extra_properties.find { |x| x.name == name }
    if [true, false].include? value
      value = (value ? "Yes" : "No")
    end

    if a.nil?
      self.extra_properties.build(name: name, value: value) unless value.blank?
    else
      if value.blank?
        a.destroy
      else
        a.update(value: value)
      end
    end
  end

  # PUNDIT
  def self.policy_class
    ApplicationPolicy
  end

end

app/controllers/admin/system/affiliates_controller.rb
class Admin::System::AffiliatesController < Admin::BaseController

  def index
    authorize Affiliate.new

    @affiliates = Affiliate.order(sort_column + " " + sort_direction)
    @affiliates = @affiliates.where("name LIKE '%#{params[:q]}%' OR code = '#{params[:q]}'") unless params[:q].blank?

    unless params[:c].blank?
      @category = Category.find_by(slug: params[:c], entity_type: :affiliate)
      @affiliates = @affiliates.joins(:affiliate_categories).where("core_affiliate_categories.category_id = #{@category.id}")
    end

    respond_to do |format|
      format.html { @affiliates = @affiliates.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Affiliate.to_csv(@affiliates) }
    end
  end

  def new
    @affiliate = authorize Affiliate.new(name: 'New affiliate', active: true, country: Cache.setting(:system, "Default Country"))
    render 'edit'
  end

  def create
    @affiliate = authorize Affiliate.new(affiliate_params)

    if @affiliate.save
      unless params[:c].blank?
        c = Category.find_by(entity_type: :affiliate, slug: params[:c])
        AffiliateCategory.create(affiliate_id: @affiliate.id, category_id: c.id) unless c.nil?
      end
      redirect_to action: 'show', id: @affiliate.id, notice: 'Affiliate was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @affiliate = authorize Affiliate.find(params[:id])
  end

  def edit
    @affiliate = authorize Affiliate.find(params[:id])
  end

  def update
    @affiliate = authorize Affiliate.find(params[:id])

    if @affiliate.update(affiliate_params)
      redirect_to action: 'show', id: @affiliate.id, notice: 'Affiliate was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @affiliate = authorize Affiliate.find(params[:id])
    @affiliate.destroy

    redirect_to action: 'index', notice: 'Affiliate has been deleted.'
  end

  def extra_properties
    @affiliate = Affiliate.find(params[:id])
    authorize @affiliate, :show?
    5.times { @affiliate.extra_properties.build }
  end

  def categories
    @affiliate = Affiliate.find(params[:id])
    authorize @affiliate, :show?
  end

  def create_categories
    authorize Affiliate, :update?

    AffiliateCategory.where(affiliate_id: params[:id]).delete_all
    category_ids = params[:category_ids]

    unless category_ids.nil?
      category_ids.each do |id|
        AffiliateCategory.create affiliate_id: params[:id], category_id: id
      end
    end

    redirect_to action: 'show', id: params[:id], notice: 'Affiliate was successfully updated.'
  end

  def products
    @affiliate = Affiliate.includes(:products, [products: :product]).find(params[:id])
    authorize @affiliate, :show?
  end

  def create_products
    authorize Affiliate, :update?

    params[:product_ids].each { |id| AffiliateProduct.create product_id: id, affiliate_id: params[:id] }
    redirect_back(fallback_location: admin_root_path)
  end

  def remove_products
    authorize Affiliate, :update?

    AffiliateProduct.delete_all id: params[:affiliate_product_ids]
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def affiliate_params
    params.require(:affiliate).permit!
  end

  def sort_column
    params[:sort] || "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/admin/system/attributes_controller.rb
class Admin::System::AttributesController < Admin::BaseController

  def index
    @attributes = Attribute.where(entity_type: params[:type]).order("sort")
  end

  def new
    @attribute = Attribute.new
    @attribute.entity_type = params[:type]
    @attribute.name = 'New attribute'
    render 'edit'
  end

  def create
    @attribute = Attribute.new(attribute_params)

    if @attribute.save
      redirect_to action: 'index', type: @attribute.entity_type, notice: 'Attribute was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @attribute = Attribute.find(params[:id])
  end

  def edit
    @attribute = Attribute.find(params[:id])
  end

  def update
    @attribute = Attribute.find(params[:id])

    if @attribute.update(attribute_params)
      redirect_to action: 'index', type: @attribute.entity_type, notice: 'Attribute was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @attribute = Attribute.find(params[:id])
    @attribute.destroy
    redirect_to action: 'index', type: @attribute.entity_type, notice: 'Attribute has been deleted.'
  end


  private

  def attribute_params
    params.require(:attribute).permit!
  end


end

app/controllers/admin/system/categories_controller.rb
class Admin::System::CategoriesController < Admin::BaseController

  def index
    @categories = Category.select("id, name, code, parent_id, slug, sort, hidden")
                          .where(entity_type: params[:type])
                          .order(:sort)
  end

  def new
    @category = Category.new entity_type: params[:type], parent_id: params[:parent_id], name: 'New category'

    @category.sort = Category.where(entity_type: params[:type], parent_id: params[:parent_id]).maximum(:sort)
    @category.sort = 0 if @category.sort.nil?
    @category.sort = @category.sort + 1

    render 'edit'
  end

  def create
    @category = Category.new(category_params)

    if @category.save
      redirect_to action: 'index', type: @category.entity_type, notice: 'Category was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @category = Category.find(params[:id])
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
      Rails.cache.delete @category
      redirect_to action: 'index', type: @category.entity_type, notice: 'Category was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @category = Category.find(params[:id])

    Rails.cache.delete @category
    @category.destroy

    redirect_to action: 'index', type: @category.entity_type, notice: 'Category has been deleted.'
  end


  private

  def category_params
    params.require(:category).permit!
  end

end

app/controllers/admin/system/domains_controller.rb
class Admin::System::DomainsController < Admin::BaseController

  def index
    authorize Domain.new
    @domains = Domain.order(:name)

    respond_to do |format|
      format.html { @domains = @domains.paginate(page: params[:page], per_page: @per_page) }
      format.csv { send_data Domain.to_csv(@domains) }
    end
  end

  def new
    @domain = authorize Domain.new(name: 'New domain')
    render 'edit'
  end

  def create
    @domain = authorize Domain.new(domain_params)

    if @domain.save
      Rails.cache.delete :domains
      redirect_to action: 'index', notice: 'Domain was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @domain = authorize Domain.find(params[:id])
  end

  def edit
    @domain = authorize Domain.find(params[:id])
  end

  def update
    @domain = authorize Domain.find(params[:id])

    if @domain.update(domain_params)
      Rails.cache.delete :domains
      redirect_to action: 'index', notice: 'Domain was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @domain = authorize Domain.find(params[:id])
    @domain.destroy

    Rails.cache.delete :domains
    redirect_to action: 'index', notice: 'Domain has been deleted.'
  end

  def set_current
    cookies[:domain_id] = {:value => params[:id], :expires => 1.year.from_now}
    redirect_back(fallback_location: admin_root_path)
  end


  private

  def domain_params
    params.require(:domain).permit!
  end
end

app/controllers/admin/system/event_types_controller.rb
class Admin::System::EventTypesController < Admin::BaseController

  def index
    authorize EventType.new
    @event_types = EventType.order(:name)
                            .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @event_type = authorize EventType.new
    render 'edit'
  end

  def create
    @event_type = authorize EventType.new(event_type_params)

    if @event_type.save
      redirect_to action: 'index', notice: 'Event Type was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @event_type = authorize EventType.find(params[:id])
  end

  def edit
    @event_type = authorize EventType.find(params[:id])
  end

  def update
    @event_type = authorize EventType.find(params[:id])

    if @event_type.update(event_type_params)
      redirect_to action: 'index', notice: 'Event Type was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @event_type = authorize EventType.find(params[:id])
    @event_type.destroy
    redirect_to action: 'index', notice: 'Event Type has been deleted.'
  end


  private

  def event_type_params
    params.require(:event_type).permit!
  end

end

app/controllers/admin/system/events_controller.rb
class Admin::System::EventsController < Admin::BaseController
  def index
    authorize Event.new
    @events = Event.includes(:event_type)
                   .order(created_at: :desc)
                   .paginate(page: params[:page], per_page: @per_page)
  end

  def new
    @event = authorize Event.new
    render 'edit'
  end

  def create
    @event = authorize Event.new(event_params)

    if @event.save
      redirect_to action: 'index', notice: 'Event was successfully created.'
    else
      render 'edit'
    end
  end

  def show
    @event = authorize Event.find(params[:id])
  end

  def edit
    @event = authorize Event.find(params[:id])
  end

  def update
    @event = authorize Event.find(params[:id])

    if @event.update(event_params)
      redirect_to action: 'index', notice: 'Event was successfully updated.'
    else
      render 'edit'
    end
  end

  def destroy
    @event = authorize Event.find(params[:id])
    @event.destroy
    redirect_to action: 'index', notice: 'Event has been deleted.'
  end

  def resend
    @event = Event.find(params[:id])
    @event.update_column(:processed_at, nil)
    flash[:info] = "Event has been re-dispatched."
    redirect_back(fallback_location: admin_system_events_path)
  end

  private

  def event_params
    params.require(:event).permit!
  end
end

app/controllers/admin/system/extra_properties_controller.rb
class Admin::System::ExtraPropertiesController < ApplicationController

  def create

    params[:extra_properties].each do |h|
      if h[:id].blank?
        ep = ExtraProperty.new(
            extra_property_id: h[:extra_property_id],
            extra_property_type: h[:extra_property_type],
            name: h[:name],
            value: h[:value],
            sort: h[:sort])
      else
        ep = ExtraProperty.find(h[:id])
        ep.assign_attributes(name: h[:name], value: h[:value], sort: h[:sort])
      end

      if ep.is_empty?
        ep.destroy
      else
        ep.save
      end
    end

    flash[:info] = "Extra properties saved"
    redirect_to params[:redirect]
  end

end

app/helpers/admin/system/webauthn_credentials_helper.rb
module Admin::System::WebauthnCredentialsHelper
end

app/views/admin/system/affiliates/categories.html.erb
<style>
    form ul {
        list-style-type: none;
    }

    form li {
        margin: 10px;
        padding-top: 5px;
    }

    form li input {
        position: relative;
        top: -4px;
    }
</style>

<h2><i class="fa fa-rocket"></i> <%= @affiliate.name %></h2>
<hr>

<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_system_affiliate_path(@affiliate) %></li>
  <li class="active"><a href="#">Categories</a></li>
  <li><%= link_to "Extra Properties", extra_properties_admin_system_affiliate_path(@affiliate) %></li>
</ul>


<form action="/admin/system/affiliates/<%= params[:id] %>/categories" method="post">
  <%= token_tag %>
  <input type="hidden" name="id" value="<%= params[:id] %>">
  <% categories = Category.where(entity_type: :affiliate)
     pcats = @affiliate.categories
     top_levels = categories.select { |c| c.parent_id == nil } %>

  <ul>
    <% top_levels.each do |cat|
      children = categories.select { |c| c.parent_id == cat.id }
      exists = pcats.any? { |c| c.id == cat.id } %>

      <li>
        <input type="checkbox" name="category_ids[]" value="<%= cat.id %>" <%= "checked='checked'" if exists %>/> &nbsp; <%= cat.name %>

        <ul>
          <% children.each do |child|
            exists = pcats.any? { |c| c.id == child.id } %>
            <li>
              <input type="checkbox" name="category_ids[]" value="<%= child.id %>" <%= "checked='checked'" if exists %>/> &nbsp; <%= child.name %>
            </li>
          <% end %>
        </ul>

      </li>
    <% end %>
  </ul>

  <button class="btn btn-primary">Update</button>
</form>


<%= content_for :title do %>
  Affiliates: <%= @affiliate.name %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li><%= link_to "Affiliates", admin_system_affiliates_path %></li>
  <li><%= link_to @affiliate.name, admin_system_affiliate_path(@affiliate) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/system/affiliates/edit.html.erb
<style>
    input.boolean {
        margin: 0;
    }
</style>

<h2><i class="fa fa-rocket"></i> <%= @affiliate.name %></h2>
<hr>

<% unless @affiliate.id.nil? %>
  <ul class="nav nav-tabs" style="margin-bottom: 20px;">
    <li class="active"><a href="#">Summary</a></li>
    <li><%= link_to "Categories", categories_admin_system_affiliate_path(@affiliate) %></li>
    <li><%= link_to "Extra Properties", extra_properties_admin_system_affiliate_path(@affiliate) %></li>
  </ul>
<% end %>

<%= simple_form_for [:admin, :system, @affiliate] do |f| %>

  <input type="hidden" name="c" value="<%= params[:c] %>">

  <%= render 'admin/shared/error_messages', object: f.object %>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :name %>
      <%= f.input :slug %>
      <%= f.input :code %>
      <%= f.input :tag_list, as: :tags %>
      <%= f.input :contact_person %>
      <%= f.input :street1 %>
      <%= f.input :street2 %>
      <%= f.input :city %>
      <%= f.input :state %>
      <%= f.input :zip %>
      <%= f.input :country %>
      <%= f.input :phone %>
      <%= f.input :fax %>
      <%= f.input :email %>
      <%= f.input :website %>
      <%= f.input :api_key %>
    </div>

    <div class="col-md-6">

      <div class="panel panel-default options-panel">
        <div class="panel-heading">Options</div>
        <div class="panel-body">
          <div class="row">
            <div class="col-md-6"><%= f.input_field :featured %> &nbsp; Featured</div>
            <div class="col-md-6"><%= f.input_field :active %> &nbsp; Active</div>
            <div class="col-md-6"><%= f.input_field :free_shipping %> &nbsp; Free Shipping</div>
            <div class="col-md-6"><%= f.input_field :tax_exempt %> &nbsp; Tax Exempt</div>
            <div class="col-md-6"><%= f.input_field :disable_invoicing %> &nbsp; Disable Invoicing</div>
            <div class="col-md-6"><%= f.input_field :enable_edi %> &nbsp; Enable EDI</div>
            <div class="col-md-6"><%= f.input_field :tracks_inventory %> &nbsp; Tracks Inventory</div>
            <div class="col-md-6"><%= f.input_field :requires_approval %> &nbsp; Requires Approval</div>
          </div>
        </div>
      </div>

      <div class="panel panel-success options-panel">
        <div class="panel-heading">Billing</div>
        <div class="panel-body">
          <div class="row">
            <%= f.input :transaction_fee %>
            <%= f.input :transaction_percent %>
            <%= f.input :discount_percent %>
            <%= f.input :markup_percent %>
            <%= f.input :payment_terms %>
            <%= f.input :tax_id, label: "Tax ID" %>
          </div>
        </div>
      </div>

      <%= ckfinder_input(@affiliate, "logo") %>
    </div>

    <div class="col-md-12" style="margin-top: 20px;">
      <h4>Short Description</h4>
      <%= f.input_field :summary, class: "form-control text", rows: 3 %>
      <br>
      <h4>Long Description</h4>
      <%= ckeditor_input_field(@affiliate, "description") %>
      <br>
      <%= button_tag "Save changes", :class => "btn btn-primary", data: {disable_with: "<i class='fa fa-spinner fa-spin'></i> Please wait ..."} %>
    </div>
  </div>

<% end %>


<%= content_for :title do %>
  Affiliates: <%= @affiliate.name %>
<% end %>


<% content_for :menu do
  render "admin/shared/system_menu"
end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li><%= link_to "Affiliates", admin_system_affiliates_path %></li>
  <% if @affiliate.id.nil? %>
    <li class="active"><%= @affiliate.name %></li>
  <% else %>
    <li><%= link_to @affiliate.name, admin_system_affiliate_path(@affiliate) %></li>
    <li class="active">edit</li>
  <% end %>
<% end %>


<% content_for :head do %>
  <% static_url = Cache.setting(Rails.configuration.domain_id, :system, 'Static Files Url') %>
  <script>

      <% unless @affiliate.persisted? %>
      $(document).ready(function () {
          $("#affiliate_name").select();
      });
      <% end %>

      function BrowseServer() {
          // You can use the "CKFinder" class to render CKFinder in a page:
          var finder = new CKFinder({connectorPath: '<%= static_url  %>/ckfinder/core/connector/php/connector.php'});
          //finder.basePath = '../';	// The path for the installation of CKFinder (default = "/ckfinder/").
          finder.selectActionFunction = SetFileField;
          finder.popup();
      }

      // This is a sample function which is called when a file is selected in CKFinder.
      function SetFileField(fileUrl) {
          document.getElementById('affiliate_logo').value = fileUrl.substring(<%= static_url.length +  5 %>);
      }
  </script>
<% end %>

app/views/admin/system/affiliates/extra_properties.html.erb
<h2><i class="fa fa-rocket"></i> <%= @affiliate.name %></h2>
<hr>

<ul class="nav nav-tabs">
  <li><%= link_to "Summary", edit_admin_system_affiliate_path(@affiliate) %></li>
  <li><%= link_to "Categories", categories_admin_system_affiliate_path(@affiliate) %></li>
  <li class="active"><%= link_to "Extra Properties", '#' %></li>
</ul>

<%= render 'admin/shared/extra_properties_list', object: @affiliate, redirect: admin_system_affiliate_path(@affiliate) %>



<%= content_for :title do %>
  Affiliates: <%= @affiliate.name %>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li><%= link_to "Affiliates", admin_system_affiliates_path %></li>
  <li><%= link_to @affiliate.name, admin_system_affiliate_path(@affiliate) %></li>
  <li class="active">edit</li>
<% end %>

app/views/admin/system/affiliates/index.html.erb
<div class="pull-right">
  <form style="display: inline-block; margin-right: 20px;" action="" method="get" id="category-form">
    <%= select_tag("c", options_from_collection_for_select(Category.where(entity_type: "affiliate"), :slug, :name, params[:c]), include_blank: '- all affiliates -') %>
  </form>
  <%= link_to new_admin_system_affiliate_path(c: params[:c]), class: 'btn btn-sm btn-default' do %>
    <i class="fa fa-plus"></i> New affiliate
  <% end %>
  <%= link_to admin_system_categories_path(type: :affiliate), class: 'btn btn-sm btn-default' do %>
    <i class="fa fa-list-ul"></i> Setup categories
  <% end %>
</div>

<h2><i class="fa fa-rocket"></i> <%= @category.nil? ? "Affiliates" : @category.name %></h2>
<hr>

<%= render "admin/shared/search_results_header", object: @affiliates %>

<%= will_paginate @affiliates %>
<table class="table table-striped table-condensed">
  <tr>
    <th><%= sortable "id", "ID" %></td>
    <th><%= sortable "name" %></th>
    <th><%= sortable "contact_person" %></th>
    <th><%= sortable "phone" %></th>
    <th><%= sortable "city" %></th>
    <th><%= sortable "created_at" %></th>
    <th class="actions">&nbsp;</th>
  </tr>
  <% @affiliates.each do |affiliate| %>
    <tr>
      <td><%= affiliate.id %></td>
      <td><%= link_to affiliate.name, admin_system_affiliate_path(affiliate) %></td>
      <td><%= affiliate.contact_person %></td>
      <td><%= affiliate.phone %></td>
      <td><%= affiliate.city %>, <%= affiliate.state %></td>
      <td><%= systime affiliate.created_at unless affiliate.created_at.nil? %></td>
      <td class="actions">
        <%= link_to "edit", edit_admin_system_affiliate_path(affiliate) %> &nbsp;
        <%= link_to "delete", {action: "destroy", id: affiliate.id}, method: :delete, data: {confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>

<%= render 'admin/shared/table_summary', data: @affiliates %>


<% content_for :title do %>
  Affiliates
<% end %>


<% content_for :head do %>
  <script>
      $(document).ready(function () {
          $('#category-form select').change(function () {
              $("#category-form").submit();
          });
      });
  </script>
<% end %>


<% content_for :breadcrumbs do %>
  <li><a href="#">System</a></li>
  <li class="active">Affiliates</li>
<% end %>